### ISSUE TITLE
Make getting on IRC easier

### ISSUE THREAD

**Issue by didlix** [gameranonymous/frontend#12]
Link to freenode's web client for IRC from the homepage? Ideally direct into our channel. Also, plug irccloud.com which has good iPhone and Android clients.

**Comment by typed-hole** [comment]
I really like the web client link idea. Wouldn't it be possible to embed the chat in a page here as well? Actually downloading and setting up an IRC client is "techy" and difficult for a lot of people. Although we could still (apart from the web client) write or copy a guide (and maybe adjust it) for those who would be interested!

**Comment by didlix** [comment]
Submit a pull request with irc.html added to the site?

**Comment by didlix** [comment]
3ff3bee1f84396a06a0994e58d9265c827bcd9ff

**Comment by didlix** [comment]
Guess the above may have solved this for people. Closing this for now.
